idf_component_register(
    SRCS 
        "main.cpp" 
        "main_gcs.cpp" 
        "system_init.cpp"
    INCLUDE_DIRS "."
    REQUIRES
        nav
        drivers
        app_hal
        control
        telemetry
        logging
        power
        config_mgr
        watchdog
        bit
        rf_mapping
        cli
        comms
        app_update
        freertos
        esp_common
        esp_hw_support
        esp_system
        esp_timer
        nvs_flash
        spi_flash
        driver
        esp_driver_usb_serial_jtag
        espcoredump
        esp_partition
        sdmmc
        fatfs
        log
        esp_wifi
)
