idf_component_register(
    SRCS
        "src/bno085.cpp"
        "src/imu_attitude.cpp"
        "src/bmp585.cpp"
        "src/ngps01.cpp"
        "src/sdp31.cpp"
        "src/sgp41.cpp"
        "src/sht4x.cpp"
        "src/ina260.cpp"
        "src/max17048.cpp"
        "src/cc1101.cpp"
        "src/dshot.cpp"
        "src/servo.cpp"
    INCLUDE_DIRS
        "include"
    REQUIRES
        app_hal
        nav
        driver
        esp_common
        log
        freertos
        esp_timer
        esp_driver_rmt
        esp_driver_ledc
)
